---

- name: Test distribution
  assert:
    that: ansible_os_family == "RedHat"

- name: Create Elasticsearch YUM repo file
  yum_repository:
    name: elastic
    description: Elastic YUM repo
    baseurl: "{{ elasticsearch_yum_repo_url }}"
    gpgkey: "{{ elasticsearch_yum_repo_key }}"
    params: "{{ elasticsearch_yum_repo_params }}"
  tags:
    - elasticsearch_pkg

- name: Install Elasticsearch package
  package:
    name: "{{ elasticsearch_pkg }}"
  notify:
    - Restart Elasticsearch service
  tags:
    - elasticsearch_pkg

- name: Install additional Elasticsearch packages
  package:
    name: "{{ item }}"
  with_items: "{{ elasticsearch_additional_pkgs }}"
  notify:
    - Restart Elasticsearch service
  tags:
    - elasticsearch_pkg

- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: "{{ elasticsearch_config_file }}"
  notify:
    - Restart Elasticsearch service
  tags:
    - elasticsearch_config

- name: Install Elasticsearch scripts
  template:
    src: script.j2
    dest: "{{ elasticsearch_scripts_path }}/{{ item.key }}"
  with_dict: "{{ elasticsearch_scripts }}"
  notify:
    - Restart Elasticsearch service
  tags:
    - elasticsearch_config
    - elasticsearch_scripts

- name: Configure Elasticsearch JVM options
  template:
    src: jvm.options.j2
    dest: "{{ elasticsearch_jvm_options_file }}"
  notify:
    - Restart Elasticsearch service
  tags:
    - elasticsearch_config
    - elasticsearch_jvm_options

- name: Configure Elasticsearch sysconfig
  template:
    src: elasticsearch.sysconfig.j2
    dest: "{{ elasticsearch_sysconfig_file }}"
  notify:
    - Restart Elasticsearch service
  tags:
    - elasticsearch_config
    - elasticsearch_sysconfig

- name: Enable Elasticsearch service
  service:
    name: "{{ elasticsearch_service }}"
    enabled: yes
  tags:
    - elasticsearch_service

- name: Start Elasticsearch service
  service:
    name: "{{ elasticsearch_service }}"
    state: started
  register: elasticsearch_service_started
  tags:
    - elasticsearch_service
